// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xfury/dvm/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
// Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
// Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryPubKeysRequest is the request type for the public keys list query.
// Query/PubKeys RPC method.
type QueryPubKeysRequest struct {
}

func (m *QueryPubKeysRequest) Reset()         { *m = QueryPubKeysRequest{} }
func (m *QueryPubKeysRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPubKeysRequest) ProtoMessage()    {}
func (*QueryPubKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{2}
}
func (m *QueryPubKeysRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPubKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPubKeysRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPubKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPubKeysRequest.Merge(m, src)
}
func (m *QueryPubKeysRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPubKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPubKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPubKeysRequest proto.InternalMessageInfo

// QueryPubKeysResponse is the response type for the public keys list query.
// Query/PubKeys RPC method.
type QueryPubKeysResponse struct {
	// list is the list of allowed public keys.
	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (m *QueryPubKeysResponse) Reset()         { *m = QueryPubKeysResponse{} }
func (m *QueryPubKeysResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPubKeysResponse) ProtoMessage()    {}
func (*QueryPubKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{3}
}
func (m *QueryPubKeysResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPubKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPubKeysResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPubKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPubKeysResponse.Merge(m, src)
}
func (m *QueryPubKeysResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPubKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPubKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPubKeysResponse proto.InternalMessageInfo

func (m *QueryPubKeysResponse) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

// QueryActivePublicKeysChangeProposalRequest is the request type for the
// Query/ActivePublicKeysChangeProposal RPC method.
type QueryActivePublicKeysChangeProposalRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryActivePublicKeysChangeProposalRequest) Reset() {
	*m = QueryActivePublicKeysChangeProposalRequest{}
}
func (m *QueryActivePublicKeysChangeProposalRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryActivePublicKeysChangeProposalRequest) ProtoMessage() {}
func (*QueryActivePublicKeysChangeProposalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{4}
}
func (m *QueryActivePublicKeysChangeProposalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivePublicKeysChangeProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivePublicKeysChangeProposalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivePublicKeysChangeProposalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalRequest.Merge(m, src)
}
func (m *QueryActivePublicKeysChangeProposalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivePublicKeysChangeProposalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivePublicKeysChangeProposalRequest proto.InternalMessageInfo

func (m *QueryActivePublicKeysChangeProposalRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryActivePublicKeysChangeProposalResponse is the response type for the
// Query/ActivePublicKeysChangeProposal RPC method.
type QueryActivePublicKeysChangeProposalResponse struct {
	// proposal holds the active proposal.
	Proposal PublicKeysChangeProposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal"`
}

func (m *QueryActivePublicKeysChangeProposalResponse) Reset() {
	*m = QueryActivePublicKeysChangeProposalResponse{}
}
func (m *QueryActivePublicKeysChangeProposalResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryActivePublicKeysChangeProposalResponse) ProtoMessage() {}
func (*QueryActivePublicKeysChangeProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{5}
}
func (m *QueryActivePublicKeysChangeProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivePublicKeysChangeProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivePublicKeysChangeProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivePublicKeysChangeProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalResponse.Merge(m, src)
}
func (m *QueryActivePublicKeysChangeProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivePublicKeysChangeProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivePublicKeysChangeProposalResponse proto.InternalMessageInfo

func (m *QueryActivePublicKeysChangeProposalResponse) GetProposal() PublicKeysChangeProposal {
	if m != nil {
		return m.Proposal
	}
	return PublicKeysChangeProposal{}
}

// QueryActivePublicKeysChangeProposalsRequest is the request type for the
// Query/ActivePublicKeysChangeProposals RPC method.
type QueryActivePublicKeysChangeProposalsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActivePublicKeysChangeProposalsRequest) Reset() {
	*m = QueryActivePublicKeysChangeProposalsRequest{}
}
func (m *QueryActivePublicKeysChangeProposalsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryActivePublicKeysChangeProposalsRequest) ProtoMessage() {}
func (*QueryActivePublicKeysChangeProposalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{6}
}
func (m *QueryActivePublicKeysChangeProposalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivePublicKeysChangeProposalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivePublicKeysChangeProposalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivePublicKeysChangeProposalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalsRequest.Merge(m, src)
}
func (m *QueryActivePublicKeysChangeProposalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivePublicKeysChangeProposalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivePublicKeysChangeProposalsRequest proto.InternalMessageInfo

func (m *QueryActivePublicKeysChangeProposalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryActivePublicKeysChangeProposalsResponse is the response type for the
// Query/ActivePublicKeysChangeProposals RPC method.
type QueryActivePublicKeysChangeProposalsResponse struct {
	// proposals hold the active proposals.
	Proposals  []PublicKeysChangeProposal `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals"`
	Pagination *query.PageResponse        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActivePublicKeysChangeProposalsResponse) Reset() {
	*m = QueryActivePublicKeysChangeProposalsResponse{}
}
func (m *QueryActivePublicKeysChangeProposalsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryActivePublicKeysChangeProposalsResponse) ProtoMessage() {}
func (*QueryActivePublicKeysChangeProposalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{7}
}
func (m *QueryActivePublicKeysChangeProposalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivePublicKeysChangeProposalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivePublicKeysChangeProposalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivePublicKeysChangeProposalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalsResponse.Merge(m, src)
}
func (m *QueryActivePublicKeysChangeProposalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivePublicKeysChangeProposalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivePublicKeysChangeProposalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivePublicKeysChangeProposalsResponse proto.InternalMessageInfo

func (m *QueryActivePublicKeysChangeProposalsResponse) GetProposals() []PublicKeysChangeProposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

func (m *QueryActivePublicKeysChangeProposalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// FinishedPublicKeysChangeProposal is the request type for the
// Query/FinishedPublicKeysChangeProposal RPC method.
type QueryFinishedPublicKeysChangeProposalRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryFinishedPublicKeysChangeProposalRequest) Reset() {
	*m = QueryFinishedPublicKeysChangeProposalRequest{}
}
func (m *QueryFinishedPublicKeysChangeProposalRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryFinishedPublicKeysChangeProposalRequest) ProtoMessage() {}
func (*QueryFinishedPublicKeysChangeProposalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{8}
}
func (m *QueryFinishedPublicKeysChangeProposalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFinishedPublicKeysChangeProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFinishedPublicKeysChangeProposalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFinishedPublicKeysChangeProposalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalRequest.Merge(m, src)
}
func (m *QueryFinishedPublicKeysChangeProposalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFinishedPublicKeysChangeProposalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFinishedPublicKeysChangeProposalRequest proto.InternalMessageInfo

func (m *QueryFinishedPublicKeysChangeProposalRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// FinishedPublicKeysChangeProposal is the response type for the
// Query/FinishedPublicKeysChangeProposal RPC method.
type QueryFinishedPublicKeysChangeProposalResponse struct {
	// proposal holds the finished proposal.
	Proposal PublicKeysChangeFinishedProposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal"`
}

func (m *QueryFinishedPublicKeysChangeProposalResponse) Reset() {
	*m = QueryFinishedPublicKeysChangeProposalResponse{}
}
func (m *QueryFinishedPublicKeysChangeProposalResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryFinishedPublicKeysChangeProposalResponse) ProtoMessage() {}
func (*QueryFinishedPublicKeysChangeProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{9}
}
func (m *QueryFinishedPublicKeysChangeProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFinishedPublicKeysChangeProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFinishedPublicKeysChangeProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFinishedPublicKeysChangeProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalResponse.Merge(m, src)
}
func (m *QueryFinishedPublicKeysChangeProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFinishedPublicKeysChangeProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFinishedPublicKeysChangeProposalResponse proto.InternalMessageInfo

func (m *QueryFinishedPublicKeysChangeProposalResponse) GetProposal() PublicKeysChangeFinishedProposal {
	if m != nil {
		return m.Proposal
	}
	return PublicKeysChangeFinishedProposal{}
}

// QueryFinishedPublicKeysChangeProposalsRequest is the request type for the
// Query/FinishedPublicKeysChangeProposals RPC method.
type QueryFinishedPublicKeysChangeProposalsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryFinishedPublicKeysChangeProposalsRequest) Reset() {
	*m = QueryFinishedPublicKeysChangeProposalsRequest{}
}
func (m *QueryFinishedPublicKeysChangeProposalsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryFinishedPublicKeysChangeProposalsRequest) ProtoMessage() {}
func (*QueryFinishedPublicKeysChangeProposalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{10}
}
func (m *QueryFinishedPublicKeysChangeProposalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFinishedPublicKeysChangeProposalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFinishedPublicKeysChangeProposalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsRequest.Merge(m, src)
}
func (m *QueryFinishedPublicKeysChangeProposalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFinishedPublicKeysChangeProposalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsRequest proto.InternalMessageInfo

func (m *QueryFinishedPublicKeysChangeProposalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryFinishedPublicKeysChangeProposalsResponse is the response type for the
// Query/FinishedPublicKeysChangeProposals RPC method.
type QueryFinishedPublicKeysChangeProposalsResponse struct {
	// proposals hold the finished proposals.
	Proposals  []PublicKeysChangeFinishedProposal `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals"`
	Pagination *query.PageResponse                `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryFinishedPublicKeysChangeProposalsResponse) Reset() {
	*m = QueryFinishedPublicKeysChangeProposalsResponse{}
}
func (m *QueryFinishedPublicKeysChangeProposalsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryFinishedPublicKeysChangeProposalsResponse) ProtoMessage() {}
func (*QueryFinishedPublicKeysChangeProposalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea3db32381b868, []int{11}
}
func (m *QueryFinishedPublicKeysChangeProposalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFinishedPublicKeysChangeProposalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFinishedPublicKeysChangeProposalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsResponse.Merge(m, src)
}
func (m *QueryFinishedPublicKeysChangeProposalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFinishedPublicKeysChangeProposalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFinishedPublicKeysChangeProposalsResponse proto.InternalMessageInfo

func (m *QueryFinishedPublicKeysChangeProposalsResponse) GetProposals() []PublicKeysChangeFinishedProposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

func (m *QueryFinishedPublicKeysChangeProposalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "furysports.xfury.dvm.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "furysports.xfury.dvm.QueryParamsResponse")
	proto.RegisterType((*QueryPubKeysRequest)(nil), "furysports.xfury.dvm.QueryPubKeysRequest")
	proto.RegisterType((*QueryPubKeysResponse)(nil), "furysports.xfury.dvm.QueryPubKeysResponse")
	proto.RegisterType((*QueryActivePublicKeysChangeProposalRequest)(nil), "furysports.xfury.dvm.QueryActivePublicKeysChangeProposalRequest")
	proto.RegisterType((*QueryActivePublicKeysChangeProposalResponse)(nil), "furysports.xfury.dvm.QueryActivePublicKeysChangeProposalResponse")
	proto.RegisterType((*QueryActivePublicKeysChangeProposalsRequest)(nil), "furysports.xfury.dvm.QueryActivePublicKeysChangeProposalsRequest")
	proto.RegisterType((*QueryActivePublicKeysChangeProposalsResponse)(nil), "furysports.xfury.dvm.QueryActivePublicKeysChangeProposalsResponse")
	proto.RegisterType((*QueryFinishedPublicKeysChangeProposalRequest)(nil), "furysports.xfury.dvm.QueryFinishedPublicKeysChangeProposalRequest")
	proto.RegisterType((*QueryFinishedPublicKeysChangeProposalResponse)(nil), "furysports.xfury.dvm.QueryFinishedPublicKeysChangeProposalResponse")
	proto.RegisterType((*QueryFinishedPublicKeysChangeProposalsRequest)(nil), "furysports.xfury.dvm.QueryFinishedPublicKeysChangeProposalsRequest")
	proto.RegisterType((*QueryFinishedPublicKeysChangeProposalsResponse)(nil), "furysports.xfury.dvm.QueryFinishedPublicKeysChangeProposalsResponse")
}

func init() { proto.RegisterFile("xfury/dvm/query.proto", fileDescriptor_c1ea3db32381b868) }

var fileDescriptor_c1ea3db32381b868 = []byte{
	// 705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xc1, 0x4f, 0x13, 0x4f,
	0x14, 0xc7, 0x3b, 0xfd, 0xf1, 0x43, 0x18, 0x13, 0x63, 0x1e, 0x25, 0x92, 0xd5, 0x2c, 0xb8, 0x21,
	0x50, 0x2b, 0xcc, 0x0a, 0xc6, 0x83, 0x89, 0x51, 0x01, 0x83, 0x07, 0x0f, 0x96, 0x5e, 0x8c, 0x5e,
	0xc8, 0x6c, 0x3b, 0x2c, 0x13, 0xdb, 0x9d, 0xa5, 0xb3, 0x5b, 0xad, 0x46, 0x0f, 0x9e, 0x3c, 0x9a,
	0xf8, 0x4f, 0x11, 0x4f, 0x44, 0x3c, 0x18, 0x4d, 0x0c, 0x01, 0xff, 0x10, 0xb3, 0x33, 0xd3, 0x96,
	0x0a, 0xa5, 0x6b, 0xab, 0xb7, 0xcd, 0xcc, 0x7b, 0xdf, 0xef, 0xfb, 0xbc, 0x79, 0x7d, 0x29, 0xce,
	0x6d, 0xc5, 0xf5, 0xa6, 0x5b, 0x69, 0xd4, 0xdc, 0x9d, 0x98, 0xd5, 0x9b, 0x24, 0xac, 0x8b, 0x48,
	0xc0, 0x44, 0x72, 0x2a, 0x43, 0x51, 0x8f, 0x24, 0x49, 0x3e, 0x49, 0xa5, 0x51, 0xb3, 0x72, 0xbe,
	0xf0, 0x85, 0xba, 0x77, 0x93, 0x2f, 0x1d, 0x6a, 0x15, 0xca, 0x42, 0xd6, 0x84, 0x74, 0x3d, 0x2a,
	0x99, 0xd6, 0x70, 0x1b, 0x4b, 0x1e, 0x8b, 0xe8, 0x92, 0x1b, 0x52, 0x9f, 0x07, 0x34, 0xe2, 0x22,
	0x30, 0xb1, 0x57, 0x7c, 0x21, 0xfc, 0x2a, 0x73, 0x69, 0xc8, 0x5d, 0x1a, 0x04, 0x22, 0x52, 0x97,
	0xd2, 0xdc, 0x4e, 0xb6, 0x4b, 0x09, 0x69, 0x9d, 0xd6, 0x5a, 0xc7, 0x97, 0x3a, 0xc7, 0x75, 0x11,
	0x0a, 0x49, 0xab, 0xfa, 0xc2, 0xc9, 0x61, 0xd8, 0x48, 0xfc, 0x8a, 0x2a, 0xba, 0xc4, 0x76, 0x62,
	0x26, 0x23, 0xa7, 0x88, 0x27, 0xba, 0x4e, 0x65, 0x28, 0x02, 0xc9, 0xe0, 0x36, 0x1e, 0xd5, 0xaa,
	0x53, 0x68, 0x06, 0xe5, 0xcf, 0x2f, 0x5f, 0x26, 0xa7, 0x20, 0x12, 0x9d, 0xb4, 0x3a, 0xb2, 0xfb,
	0x63, 0x3a, 0x53, 0x32, 0x09, 0xce, 0x64, 0x4b, 0x31, 0xf6, 0x1e, 0xb1, 0x66, 0xdb, 0xa8, 0x80,
	0x73, 0xdd, 0xc7, 0xc6, 0x09, 0xf0, 0x48, 0x95, 0xcb, 0x68, 0x0a, 0xcd, 0xfc, 0x97, 0x1f, 0x2f,
	0xa9, 0x6f, 0xe7, 0x0e, 0x2e, 0xa8, 0xd8, 0x95, 0x72, 0xc4, 0x1b, 0xac, 0x18, 0x7b, 0x55, 0x5e,
	0x4e, 0x92, 0xd6, 0xb6, 0x69, 0xe0, 0xb3, 0xa2, 0xe1, 0x32, 0xca, 0x70, 0x01, 0x67, 0x79, 0x45,
	0xd5, 0x39, 0x52, 0xca, 0xf2, 0x8a, 0xf3, 0x16, 0x5f, 0x4f, 0x95, 0x6d, 0x0a, 0x78, 0x8c, 0xc7,
	0x5a, 0x9d, 0x32, 0xb0, 0x8b, 0xa7, 0xc3, 0xf6, 0x10, 0x32, 0xf8, 0x6d, 0x11, 0x27, 0x4e, 0xe5,
	0xdf, 0x6a, 0x0c, 0xac, 0x63, 0xdc, 0x79, 0x79, 0x53, 0xc1, 0x1c, 0xd1, 0x63, 0x42, 0x92, 0x31,
	0x21, 0x7a, 0xd4, 0xcc, 0x98, 0x90, 0x22, 0xf5, 0x99, 0xc9, 0x2d, 0x1d, 0xcb, 0x74, 0x3e, 0x21,
	0xbc, 0x90, 0xce, 0xd7, 0x80, 0x6f, 0xe0, 0xf1, 0x56, 0xcd, 0x52, 0xb5, 0x7f, 0x40, 0xf2, 0x8e,
	0x0a, 0x3c, 0xec, 0x62, 0xc9, 0x2a, 0x96, 0xf9, 0xbe, 0x2c, 0xba, 0x9e, 0x2e, 0x98, 0xbb, 0x86,
	0x65, 0x9d, 0x07, 0x5c, 0x6e, 0xb3, 0xca, 0x9f, 0xce, 0xc0, 0x7b, 0x84, 0x17, 0x53, 0x0a, 0x98,
	0x6e, 0x3c, 0x39, 0x31, 0x06, 0xb7, 0x52, 0x35, 0xa3, 0x6d, 0xd0, 0x6b, 0x1c, 0x5e, 0xa4, 0xac,
	0xe4, 0xaf, 0x0f, 0xc4, 0x17, 0x84, 0x49, 0x5a, 0x67, 0xd3, 0x84, 0xa7, 0x27, 0x47, 0x62, 0xa8,
	0x2e, 0xfc, 0x83, 0xd1, 0x58, 0x3e, 0x18, 0xc3, 0xff, 0x2b, 0x2c, 0x88, 0xf1, 0xa8, 0xde, 0x40,
	0x30, 0x7f, 0x6a, 0x91, 0x27, 0xd7, 0x9d, 0x95, 0xef, 0x1f, 0xa8, 0x2d, 0x9d, 0xa9, 0x77, 0xfb,
	0x3f, 0x3f, 0x66, 0x01, 0x2e, 0xba, 0xbf, 0xed, 0x59, 0x78, 0x85, 0xcf, 0x99, 0x25, 0x06, 0x67,
	0xc9, 0x75, 0xad, 0x3f, 0xeb, 0x5a, 0x8a, 0x48, 0xe3, 0x6c, 0x29, 0xe7, 0x1c, 0xc0, 0x31, 0xe7,
	0xd8, 0xdb, 0x7c, 0x9e, 0x18, 0xee, 0x23, 0x6c, 0x9f, 0xfd, 0xfb, 0x86, 0x7b, 0xbd, 0x9d, 0x52,
	0xed, 0x53, 0xeb, 0xfe, 0xe0, 0x02, 0x86, 0x80, 0x28, 0x82, 0x3c, 0xcc, 0x75, 0x08, 0xa8, 0xca,
	0xdc, 0x0c, 0x63, 0x2f, 0xe1, 0xd8, 0x6c, 0xcd, 0x85, 0xfb, 0x9a, 0x57, 0xde, 0xc0, 0x67, 0x84,
	0xa7, 0xfb, 0x6c, 0x2d, 0x18, 0xb8, 0xaa, 0xf6, 0x13, 0xac, 0x0c, 0xa1, 0x60, 0xc0, 0x0a, 0x0a,
	0x6c, 0x16, 0x9c, 0xbe, 0x60, 0x12, 0xbe, 0x23, 0x3c, 0xd3, 0xef, 0x97, 0x07, 0x67, 0xd4, 0x94,
	0x72, 0xf5, 0x59, 0xab, 0xc3, 0x48, 0x18, 0xae, 0x1b, 0x8a, 0xab, 0x00, 0xf9, 0x0e, 0xd7, 0x96,
	0xc9, 0xed, 0xf1, 0x64, 0xdf, 0x10, 0xbe, 0xda, 0x77, 0xaf, 0xc0, 0x10, 0xb5, 0xb5, 0x9f, 0x6d,
	0x6d, 0x28, 0x0d, 0x03, 0xb8, 0xa0, 0x00, 0xe7, 0x60, 0x36, 0x05, 0xa0, 0x5c, 0x7d, 0xb0, 0x7b,
	0x68, 0xa3, 0xbd, 0x43, 0x1b, 0x1d, 0x1c, 0xda, 0xe8, 0xc3, 0x91, 0x9d, 0xd9, 0x3b, 0xb2, 0x33,
	0x5f, 0x8f, 0xec, 0xcc, 0xb3, 0x82, 0xcf, 0xa3, 0xed, 0xd8, 0x23, 0x65, 0x51, 0x73, 0xb7, 0x68,
	0x90, 0x88, 0x2d, 0xea, 0xd2, 0xb4, 0xf0, 0x4b, 0x25, 0x1d, 0x35, 0x43, 0x26, 0xbd, 0x51, 0xf5,
	0xbf, 0xeb, 0xe6, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x32, 0xb9, 0x73, 0x34, 0x0a, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of PubKeys items.
	PubKeys(ctx context.Context, in *QueryPubKeysRequest, opts ...grpc.CallOption) (*QueryPubKeysResponse, error)
	// Queries an active proposal by id.
	ActivePublicKeysChangeProposal(ctx context.Context, in *QueryActivePublicKeysChangeProposalRequest, opts ...grpc.CallOption) (*QueryActivePublicKeysChangeProposalResponse, error)
	// Queries a list of active proposal items.
	ActivePublicKeysChangeProposals(ctx context.Context, in *QueryActivePublicKeysChangeProposalsRequest, opts ...grpc.CallOption) (*QueryActivePublicKeysChangeProposalsResponse, error)
	// Queries a finished proposal by id.
	FinishedPublicKeysChangeProposal(ctx context.Context, in *QueryFinishedPublicKeysChangeProposalRequest, opts ...grpc.CallOption) (*QueryFinishedPublicKeysChangeProposalResponse, error)
	// Queries a list of finished proposal items.
	FinishedPublicKeysChangeProposals(ctx context.Context, in *QueryFinishedPublicKeysChangeProposalsRequest, opts ...grpc.CallOption) (*QueryFinishedPublicKeysChangeProposalsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/xfurysports.xfury.dvm.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PubKeys(ctx context.Context, in *QueryPubKeysRequest, opts ...grpc.CallOption) (*QueryPubKeysResponse, error) {
	out := new(QueryPubKeysResponse)
	err := c.cc.Invoke(ctx, "/xfurysports.xfury.dvm.Query/PubKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActivePublicKeysChangeProposal(ctx context.Context, in *QueryActivePublicKeysChangeProposalRequest, opts ...grpc.CallOption) (*QueryActivePublicKeysChangeProposalResponse, error) {
	out := new(QueryActivePublicKeysChangeProposalResponse)
	err := c.cc.Invoke(ctx, "/xfurysports.xfury.dvm.Query/ActivePublicKeysChangeProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActivePublicKeysChangeProposals(ctx context.Context, in *QueryActivePublicKeysChangeProposalsRequest, opts ...grpc.CallOption) (*QueryActivePublicKeysChangeProposalsResponse, error) {
	out := new(QueryActivePublicKeysChangeProposalsResponse)
	err := c.cc.Invoke(ctx, "/xfurysports.xfury.dvm.Query/ActivePublicKeysChangeProposals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FinishedPublicKeysChangeProposal(ctx context.Context, in *QueryFinishedPublicKeysChangeProposalRequest, opts ...grpc.CallOption) (*QueryFinishedPublicKeysChangeProposalResponse, error) {
	out := new(QueryFinishedPublicKeysChangeProposalResponse)
	err := c.cc.Invoke(ctx, "/xfurysports.xfury.dvm.Query/FinishedPublicKeysChangeProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FinishedPublicKeysChangeProposals(ctx context.Context, in *QueryFinishedPublicKeysChangeProposalsRequest, opts ...grpc.CallOption) (*QueryFinishedPublicKeysChangeProposalsResponse, error) {
	out := new(QueryFinishedPublicKeysChangeProposalsResponse)
	err := c.cc.Invoke(ctx, "/xfurysports.xfury.dvm.Query/FinishedPublicKeysChangeProposals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of PubKeys items.
	PubKeys(context.Context, *QueryPubKeysRequest) (*QueryPubKeysResponse, error)
	// Queries an active proposal by id.
	ActivePublicKeysChangeProposal(context.Context, *QueryActivePublicKeysChangeProposalRequest) (*QueryActivePublicKeysChangeProposalResponse, error)
	// Queries a list of active proposal items.
	ActivePublicKeysChangeProposals(context.Context, *QueryActivePublicKeysChangeProposalsRequest) (*QueryActivePublicKeysChangeProposalsResponse, error)
	// Queries a finished proposal by id.
	FinishedPublicKeysChangeProposal(context.Context, *QueryFinishedPublicKeysChangeProposalRequest) (*QueryFinishedPublicKeysChangeProposalResponse, error)
	// Queries a list of finished proposal items.
	FinishedPublicKeysChangeProposals(context.Context, *QueryFinishedPublicKeysChangeProposalsRequest) (*QueryFinishedPublicKeysChangeProposalsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) PubKeys(ctx context.Context, req *QueryPubKeysRequest) (*QueryPubKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PubKeys not implemented")
}
func (*UnimplementedQueryServer) ActivePublicKeysChangeProposal(ctx context.Context, req *QueryActivePublicKeysChangeProposalRequest) (*QueryActivePublicKeysChangeProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivePublicKeysChangeProposal not implemented")
}
func (*UnimplementedQueryServer) ActivePublicKeysChangeProposals(ctx context.Context, req *QueryActivePublicKeysChangeProposalsRequest) (*QueryActivePublicKeysChangeProposalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivePublicKeysChangeProposals not implemented")
}
func (*UnimplementedQueryServer) FinishedPublicKeysChangeProposal(ctx context.Context, req *QueryFinishedPublicKeysChangeProposalRequest) (*QueryFinishedPublicKeysChangeProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishedPublicKeysChangeProposal not implemented")
}
func (*UnimplementedQueryServer) FinishedPublicKeysChangeProposals(ctx context.Context, req *QueryFinishedPublicKeysChangeProposalsRequest) (*QueryFinishedPublicKeysChangeProposalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishedPublicKeysChangeProposals not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xfurysports.xfury.dvm.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PubKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPubKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PubKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xfurysports.xfury.dvm.Query/PubKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PubKeys(ctx, req.(*QueryPubKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActivePublicKeysChangeProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActivePublicKeysChangeProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActivePublicKeysChangeProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xfurysports.xfury.dvm.Query/ActivePublicKeysChangeProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActivePublicKeysChangeProposal(ctx, req.(*QueryActivePublicKeysChangeProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActivePublicKeysChangeProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActivePublicKeysChangeProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActivePublicKeysChangeProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xfurysports.xfury.dvm.Query/ActivePublicKeysChangeProposals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActivePublicKeysChangeProposals(ctx, req.(*QueryActivePublicKeysChangeProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FinishedPublicKeysChangeProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFinishedPublicKeysChangeProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FinishedPublicKeysChangeProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xfurysports.xfury.dvm.Query/FinishedPublicKeysChangeProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FinishedPublicKeysChangeProposal(ctx, req.(*QueryFinishedPublicKeysChangeProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FinishedPublicKeysChangeProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFinishedPublicKeysChangeProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FinishedPublicKeysChangeProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xfurysports.xfury.dvm.Query/FinishedPublicKeysChangeProposals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FinishedPublicKeysChangeProposals(ctx, req.(*QueryFinishedPublicKeysChangeProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furysports.xfury.dvm.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PubKeys",
			Handler:    _Query_PubKeys_Handler,
		},
		{
			MethodName: "ActivePublicKeysChangeProposal",
			Handler:    _Query_ActivePublicKeysChangeProposal_Handler,
		},
		{
			MethodName: "ActivePublicKeysChangeProposals",
			Handler:    _Query_ActivePublicKeysChangeProposals_Handler,
		},
		{
			MethodName: "FinishedPublicKeysChangeProposal",
			Handler:    _Query_FinishedPublicKeysChangeProposal_Handler,
		},
		{
			MethodName: "FinishedPublicKeysChangeProposals",
			Handler:    _Query_FinishedPublicKeysChangeProposals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xfury/dvm/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryPubKeysRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPubKeysRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPubKeysRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPubKeysResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPubKeysResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPubKeysResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.List) > 0 {
		for iNdEx := len(m.List) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.List[iNdEx])
			copy(dAtA[i:], m.List[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.List[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryActivePublicKeysChangeProposalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivePublicKeysChangeProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivePublicKeysChangeProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryActivePublicKeysChangeProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivePublicKeysChangeProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivePublicKeysChangeProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Proposal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryActivePublicKeysChangeProposalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivePublicKeysChangeProposalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivePublicKeysChangeProposalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryActivePublicKeysChangeProposalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivePublicKeysChangeProposalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivePublicKeysChangeProposalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Proposals) > 0 {
		for iNdEx := len(m.Proposals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Proposals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryFinishedPublicKeysChangeProposalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFinishedPublicKeysChangeProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFinishedPublicKeysChangeProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryFinishedPublicKeysChangeProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFinishedPublicKeysChangeProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFinishedPublicKeysChangeProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Proposal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryFinishedPublicKeysChangeProposalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFinishedPublicKeysChangeProposalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFinishedPublicKeysChangeProposalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFinishedPublicKeysChangeProposalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFinishedPublicKeysChangeProposalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFinishedPublicKeysChangeProposalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Proposals) > 0 {
		for iNdEx := len(m.Proposals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Proposals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryPubKeysRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPubKeysResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.List) > 0 {
		for _, s := range m.List {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryActivePublicKeysChangeProposalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryActivePublicKeysChangeProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Proposal.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryActivePublicKeysChangeProposalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActivePublicKeysChangeProposalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Proposals) > 0 {
		for _, e := range m.Proposals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFinishedPublicKeysChangeProposalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryFinishedPublicKeysChangeProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Proposal.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryFinishedPublicKeysChangeProposalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFinishedPublicKeysChangeProposalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Proposals) > 0 {
		for _, e := range m.Proposals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPubKeysRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPubKeysRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPubKeysRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPubKeysResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPubKeysResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPubKeysResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.List = append(m.List, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivePublicKeysChangeProposalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivePublicKeysChangeProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Proposal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivePublicKeysChangeProposalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivePublicKeysChangeProposalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivePublicKeysChangeProposalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposals = append(m.Proposals, PublicKeysChangeProposal{})
			if err := m.Proposals[len(m.Proposals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFinishedPublicKeysChangeProposalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFinishedPublicKeysChangeProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Proposal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFinishedPublicKeysChangeProposalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFinishedPublicKeysChangeProposalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFinishedPublicKeysChangeProposalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposals = append(m.Proposals, PublicKeysChangeFinishedProposal{})
			if err := m.Proposals[len(m.Proposals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
